#!/usr/bin/env bash

set -euo pipefail

# Default is site-specific; override SMOLVLA_WORKSPACE_ROOT or SMOLVLA_REPO_ROOT on other machines.
SMOLVLA_WORKSPACE_ROOT="${SMOLVLA_WORKSPACE_ROOT:-/vol/bitbucket/aa6622}"
SMOLVLA_REPO_ROOT="${SMOLVLA_REPO_ROOT:-${SMOLVLA_WORKSPACE_ROOT}/pi05-cube-FT}"
SMOLVLA_VGG_REPO="${SMOLVLA_VGG_REPO:-${SMOLVLA_WORKSPACE_ROOT}/VGG JEPA}"
SMOLVLA_LEGACY_PI05_VENV="${SMOLVLA_LEGACY_PI05_VENV:-${SMOLVLA_REPO_ROOT}/stable-worldmodel/.venv}"

SMOLVLA_INIT_CHECKPOINT="${SMOLVLA_INIT_CHECKPOINT:-jadechoghari/smolvla_metaworld}"
SMOLVLA_BASELINE_EPISODES="${SMOLVLA_BASELINE_EPISODES:-15}"
SMOLVLA_BASELINE_VIDEO="${SMOLVLA_BASELINE_VIDEO:-true}"
SMOLVLA_BASELINE_VIDEO_LENGTH="${SMOLVLA_BASELINE_VIDEO_LENGTH:-220}"
SMOLVLA_BASELINE_VIDEO_INTERVAL="${SMOLVLA_BASELINE_VIDEO_INTERVAL:-2}"
SMOLVLA_BASELINE_DEVICE="${SMOLVLA_BASELINE_DEVICE:-auto}"
SMOLVLA_BASELINE_SEED="${SMOLVLA_BASELINE_SEED:-123}"
SMOLVLA_BASELINE_USE_AMP="${SMOLVLA_BASELINE_USE_AMP:-false}"
SMOLVLA_BASELINE_EPISODE_LENGTH="${SMOLVLA_BASELINE_EPISODE_LENGTH:-400}"
SMOLVLA_BASELINE_CMD="${SMOLVLA_BASELINE_CMD:-}"
SMOLVLA_LOCAL_ROLLOUT_EPISODES="${SMOLVLA_LOCAL_ROLLOUT_EPISODES:-60}"
SMOLVLA_FIRST_FT_STEPS="${SMOLVLA_FIRST_FT_STEPS:-6000}"
# Locked research mode: all TrainA/B/C/D start from the same base checkpoint (no progressive chain).
SMOLVLA_CHECKPOINT_POLICY="${SMOLVLA_CHECKPOINT_POLICY:-base_init_compare}"
# Optional: isolate artifacts/reports/logs under .../run_${ID}/ to avoid cross-run collisions.
SMOLVLA_RUN_SCOPE_ID="${SMOLVLA_RUN_SCOPE_ID:-}"
# Workflow JSON (`smolvla_workflow_launcher.py`): `run_id` is taken from exported `RUN_ID` or `SMOLVLA_RUN_ID`.
# `submit_workflow.sh` sets and exports `RUN_ID`; for manual launcher calls, export one of these first.
# If 1 with SMOLVLA_RUN_SCOPE_ID set, refuse to start when scoped artifact root already exists.
SMOLVLA_FAIL_ON_PATH_REUSE="${SMOLVLA_FAIL_ON_PATH_REUSE:-0}"
SMOLVLA_TRAIN_VARIANT="${SMOLVLA_TRAIN_VARIANT:-auto}"
SMOLVLA_TRAIN_DRY_RUN="${SMOLVLA_TRAIN_DRY_RUN:-0}"
SMOLVLA_TRAIN_LOG_STEPS="${SMOLVLA_TRAIN_LOG_STEPS:-100}"
SMOLVLA_TRAIN_SAVE_STEPS="${SMOLVLA_TRAIN_SAVE_STEPS:-2000}"
SMOLVLA_POLICY_REPORT_TO="${SMOLVLA_POLICY_REPORT_TO:-wandb}"
SMOLVLA_TRAIN_REPORT_TO="${SMOLVLA_TRAIN_REPORT_TO:-${SMOLVLA_POLICY_REPORT_TO}}"
SMOLVLA_WANDB_MODE="${SMOLVLA_WANDB_MODE:-offline}"

SMOLVLA_ENV_ROOT="${SMOLVLA_ENV_ROOT:-${SMOLVLA_WORKSPACE_ROOT}/.envs}"
SMOLVLA_LEGACY_ENV_DIR="${SMOLVLA_LEGACY_ENV_DIR:-${SMOLVLA_WORKSPACE_ROOT}/pi05-cube-FT/stable-worldmodel/.venv}"
SMOLVLA_LEROBOT_ENV_DIR="${SMOLVLA_LEROBOT_ENV_DIR:-${SMOLVLA_ENV_ROOT}/lerobot_mw_py310}"
SMOLVLA_JEPA_ENV_DIR="${SMOLVLA_JEPA_ENV_DIR:-${SMOLVLA_ENV_ROOT}/jepa_wms_py310}"
SMOLVLA_VGG_ENV_DIR="${SMOLVLA_VGG_ENV_DIR:-${SMOLVLA_ENV_ROOT}/vggflow_py311}"

SMOLVLA_CACHE_ROOT="${SMOLVLA_CACHE_ROOT:-${SMOLVLA_WORKSPACE_ROOT}/.cache}"
SMOLVLA_HF_HOME="${SMOLVLA_HF_HOME:-${SMOLVLA_CACHE_ROOT}/huggingface}"
SMOLVLA_PIP_CACHE="${SMOLVLA_PIP_CACHE:-${SMOLVLA_CACHE_ROOT}/pip}"
SMOLVLA_UV_CACHE="${SMOLVLA_UV_CACHE:-${SMOLVLA_CACHE_ROOT}/uv}"

SMOLVLA_REPORT_ROOT="${SMOLVLA_REPORT_ROOT:-${SMOLVLA_REPO_ROOT}/reports}"
SMOLVLA_ARTIFACT_ROOT="${SMOLVLA_ARTIFACT_ROOT:-${SMOLVLA_REPO_ROOT}/artifacts}"
SMOLVLA_DATA_ROOT="${SMOLVLA_DATA_ROOT:-${SMOLVLA_REPO_ROOT}/datasets/bridged_v30}"
# Optional TrainD: VGG aux on imagined-heavy root (default bridged val). Use SMOLVLA_TRAIN_VARIANT=d and/or SMOLVLA_ENABLE_TRAIN_D=1.
SMOLVLA_ENABLE_TRAIN_D="${SMOLVLA_ENABLE_TRAIN_D:-0}"
SMOLVLA_STAGE_D_DATA_ROOT="${SMOLVLA_STAGE_D_DATA_ROOT:-${SMOLVLA_DATA_ROOT}/val}"
SMOLVLA_LOG_ROOT="${SMOLVLA_LOG_ROOT:-${SMOLVLA_REPO_ROOT}/logs/smolve}"
SMOLVLA_LOCK_ROOT="${SMOLVLA_LOCK_ROOT:-${SMOLVLA_REPO_ROOT}/reports/environment_locks}"

SMOLVLA_DECISION_LOG="${SMOLVLA_REPORT_ROOT}/decision_log.md"
SMOLVLA_PRESET_REPORT="${SMOLVLA_REPORT_ROOT}/preflight_system_report.md"

SMOLVLA_JEPA_CKPT="${SMOLVLA_JEPA_CKPT:-jepa_wm_metaworld.pth.tar}"
SMOLVLA_JEPA_TASK="${SMOLVLA_JEPA_TASK:-push-v3}"
SMOLVLA_JEPA_SMOKE_STEPS="${SMOLVLA_JEPA_SMOKE_STEPS:-8}"
SMOLVLA_JEPA_SMOKE_FORCE_VALIDATE="${SMOLVLA_JEPA_SMOKE_FORCE_VALIDATE:-0}"
# When 1 and SMOLVLA_JEPA_EXPORT_ENABLED=1, phase07 skips jepa_smoke_check.py so torch.hub loads JEPA-WM only once (inside the exporter).
SMOLVLA_JEPA_SKIP_SMOKE_WHEN_EXPORT="${SMOLVLA_JEPA_SKIP_SMOKE_WHEN_EXPORT:-1}"
SMOLVLA_JEPA_REMOTE_REPO="${SMOLVLA_JEPA_REMOTE_REPO:-facebook/jepa-wms}"
SMOLVLA_JEPA_SOURCE="${SMOLVLA_JEPA_SOURCE:-${SMOLVLA_CACHE_ROOT}/jepa_workflow}"
# When 1, phase07 runs MetaWorld rollouts and writes trajectories under SMOLVLA_JEPA_EXPORT_OUT (bridge input).
SMOLVLA_JEPA_EXPORT_ENABLED="${SMOLVLA_JEPA_EXPORT_ENABLED:-0}"
# When 1, skip loading SmolVLA for export (empty --policy-checkpoint): avoids VLM/safetensors segfaults on some cluster stacks; rollouts use CEM/heuristic per exporter.
SMOLVLA_JEPA_EXPORT_USE_HEURISTIC_EXEC="${SMOLVLA_JEPA_EXPORT_USE_HEURISTIC_EXEC:-0}"
# When 1, jepa_cem_paired_pushv3_export uses --device cpu for WM encode/unroll (avoids CUDA+pygame/Mesa segfaults on some Slurm GPU nodes; slower).
SMOLVLA_JEPA_EXPORT_WM_ON_CPU="${SMOLVLA_JEPA_EXPORT_WM_ON_CPU:-0}"
# When 1, exporter skips torch.hub WM load (heuristic-only rollouts; still writes trajectories.pt for bridge if MetaWorld runs). Use when hub load segfaults after checkpoint init on cluster nodes.
SMOLVLA_JEPA_EXPORT_SKIP_WM="${SMOLVLA_JEPA_EXPORT_SKIP_WM:-0}"
# Exporter strict quality gates (phase07 -> jepa_cem_paired_pushv3_export.py)
SMOLVLA_JEPA_EXPORT_MAX_WM_ERROR_RATE="${SMOLVLA_JEPA_EXPORT_MAX_WM_ERROR_RATE:-0.05}"
SMOLVLA_JEPA_EXPORT_MAX_POLICY_ERROR_RATE="${SMOLVLA_JEPA_EXPORT_MAX_POLICY_ERROR_RATE:-0.05}"
SMOLVLA_JEPA_EXPORT_REQUIRE_IMAGES="${SMOLVLA_JEPA_EXPORT_REQUIRE_IMAGES:-1}"
SMOLVLA_JEPA_EXPORT_EXECUTION_POLICY="${SMOLVLA_JEPA_EXPORT_EXECUTION_POLICY:-cem_primary}"
SMOLVLA_JEPA_EXPORT_STORE_CEM_PLAN_SEQ="${SMOLVLA_JEPA_EXPORT_STORE_CEM_PLAN_SEQ:-1}"
SMOLVLA_JEPA_EXPORT_STORE_SMOLVLA_ACTION="${SMOLVLA_JEPA_EXPORT_STORE_SMOLVLA_ACTION:-1}"
# Keep full latent trajectories by default for downstream bridge/train objectives.
SMOLVLA_JEPA_EXPORT_FULL_LATENTS="${SMOLVLA_JEPA_EXPORT_FULL_LATENTS:-1}"
# When 0/false/no, SmolVLA export skips loading VLM backbone weights (smaller download; may reduce segfault risk on some stacks).
SMOLVLA_JEPA_EXPORT_POLICY_LOAD_VLM_WEIGHTS="${SMOLVLA_JEPA_EXPORT_POLICY_LOAD_VLM_WEIGHTS:-1}"
# SmolVLA policy load device for exporter: default|auto|cpu|cuda (default follows exporter --device / WM path).
SMOLVLA_JEPA_EXPORT_POLICY_DEVICE="${SMOLVLA_JEPA_EXPORT_POLICY_DEVICE:-default}"
# Headless MuJoCo render backend used by phase07 exporter.
SMOLVLA_JEPA_MUJOCO_GL="${SMOLVLA_JEPA_MUJOCO_GL:-egl}"
SMOLVLA_JEPA_PYOPENGL_PLATFORM="${SMOLVLA_JEPA_PYOPENGL_PLATFORM:-egl}"
SMOLVLA_JEPA_EXPORT_OUT="${SMOLVLA_JEPA_EXPORT_OUT:-${SMOLVLA_JEPA_SOURCE}}"
SMOLVLA_JEPA_EXPORT_EPISODES="${SMOLVLA_JEPA_EXPORT_EPISODES:-16}"
# Number of episodes written per shard payload (1 keeps memory bounded while preserving per-episode isolation).
SMOLVLA_JEPA_EXPORT_EPISODES_PER_SHARD="${SMOLVLA_JEPA_EXPORT_EPISODES_PER_SHARD:-1}"
# Memory safety guardrails for phase07 exporter; 0 disables hard RSS limit.
SMOLVLA_JEPA_EXPORT_MAX_RSS_GB="${SMOLVLA_JEPA_EXPORT_MAX_RSS_GB:-0}"
SMOLVLA_JEPA_EXPORT_RSS_LOG_INTERVAL_STEPS="${SMOLVLA_JEPA_EXPORT_RSS_LOG_INTERVAL_STEPS:-25}"
SMOLVLA_JEPA_EXPORT_MAX_STEPS="${SMOLVLA_JEPA_EXPORT_MAX_STEPS:-200}"
SMOLVLA_JEPA_EXPORT_SEED="${SMOLVLA_JEPA_EXPORT_SEED:-123}"
# CEM + WM rollout (phase07 jepa_cem_paired_pushv3_export.py)
SMOLVLA_JEPA_CEM_HORIZON="${SMOLVLA_JEPA_CEM_HORIZON:-4}"
SMOLVLA_JEPA_CEM_POP="${SMOLVLA_JEPA_CEM_POP:-8}"
SMOLVLA_JEPA_CEM_ITERS="${SMOLVLA_JEPA_CEM_ITERS:-2}"
SMOLVLA_BRIDGE_MIN_CONFIDENCE="${SMOLVLA_BRIDGE_MIN_CONFIDENCE:-0.0}"
SMOLVLA_BRIDGE_VAL_RATIO="${SMOLVLA_BRIDGE_VAL_RATIO:-0.15}"
# Planned WM-heavy split toggle (primary) + compatibility alias.
SMOLVLA_BRIDGE_WM_HEAVY_SPLIT="${SMOLVLA_BRIDGE_WM_HEAVY_SPLIT:-${SMOLVLA_BRIDGE_WM_HEAVY_SPLIT_ENABLED:-1}}"
# Planned WM-heavy split knobs (primary names).
SMOLVLA_BRIDGE_WM_HEAVY_JEPA_FRACTION="${SMOLVLA_BRIDGE_WM_HEAVY_JEPA_FRACTION:-${SMOLVLA_BRIDGE_WM_HEAVY_VAL_FRACTION:-0.60}}"
SMOLVLA_BRIDGE_WM_SCORE_MARGIN="${SMOLVLA_BRIDGE_WM_SCORE_MARGIN:-${SMOLVLA_BRIDGE_WM_HEAVY_SCORE_MARGIN:-0.00}}"
# Backward-compatible aliases.
SMOLVLA_BRIDGE_WM_HEAVY_SPLIT_ENABLED="${SMOLVLA_BRIDGE_WM_HEAVY_SPLIT_ENABLED:-${SMOLVLA_BRIDGE_WM_HEAVY_SPLIT}}"
SMOLVLA_BRIDGE_WM_HEAVY_VAL_FRACTION="${SMOLVLA_BRIDGE_WM_HEAVY_VAL_FRACTION:-${SMOLVLA_BRIDGE_WM_HEAVY_JEPA_FRACTION}}"
SMOLVLA_BRIDGE_WM_HEAVY_SCORE_MARGIN="${SMOLVLA_BRIDGE_WM_HEAVY_SCORE_MARGIN:-${SMOLVLA_BRIDGE_WM_SCORE_MARGIN}}"
SMOLVLA_BRIDGE_MIN_ACTION_LEN="${SMOLVLA_BRIDGE_MIN_ACTION_LEN:-1}"
SMOLVLA_BRIDGE_TRAIN_RATIO="${SMOLVLA_BRIDGE_TRAIN_RATIO:-0.85}"
SMOLVLA_BRIDGE_MAX_HEURISTIC_FALLBACK_RATIO="${SMOLVLA_BRIDGE_MAX_HEURISTIC_FALLBACK_RATIO:-0.10}"
SMOLVLA_BRIDGE_MIN_IMAGE_COVERAGE="${SMOLVLA_BRIDGE_MIN_IMAGE_COVERAGE:-0.95}"
SMOLVLA_BRIDGE_MIN_ACTION_STD="${SMOLVLA_BRIDGE_MIN_ACTION_STD:-0.02}"
# Keep conversion enabled by default; stage10 training expects LeRobot v3.0 datasets.
SMOLVLA_BRIDGE_NO_CONVERT_V30="${SMOLVLA_BRIDGE_NO_CONVERT_V30:-0}"

SMOLVLA_PARTITION_LIST="${SMOLVLA_PARTITION_LIST:-a100,a40,a30,t4,a16}"
SMOLVLA_DEFAULT_PARTITION="${SMOLVLA_DEFAULT_PARTITION:-a100}"
SMOLVLA_DEFAULT_TIME="${SMOLVLA_DEFAULT_TIME:-04:00:00}"

SMOLVLA_STAGE00_SLURM="stage00_preflight.slurm"
SMOLVLA_STAGE01_SLURM="stage01_install_lerobot_mw.slurm"
SMOLVLA_STAGE01B_SLURM="stage01b_install_metaworld.slurm"
SMOLVLA_STAGE02_SLURM="stage02_baseline_pushv3_eval.slurm"
SMOLVLA_STAGE03_SLURM="stage03_install_jepa_wms.slurm"
SMOLVLA_STAGE04_SLURM="stage04_bridge_dataset_build.slurm"
SMOLVLA_STAGE10_A="${SMOLVLA_STAGE10_A:-stage05_train_stageA_real_only.slurm}"
SMOLVLA_STAGE10_B="${SMOLVLA_STAGE10_B:-stage06_train_stageB_jepa_mix.slurm}"
SMOLVLA_STAGE10_C="${SMOLVLA_STAGE10_C:-stage08_train_stageC_vgg_aux.slurm}"
SMOLVLA_STAGE10_D="${SMOLVLA_STAGE10_D:-stage10_train_stageD_imagined.slurm}"

SMOLVLA_VGG_AUX_WEIGHT="${SMOLVLA_VGG_AUX_WEIGHT:-0.05}"
SMOLVLA_VGG_AUX_WARMUP_STEPS="${SMOLVLA_VGG_AUX_WARMUP_STEPS:-500}"
SMOLVLA_VGG_VALUE_HEAD_DIM="${SMOLVLA_VGG_VALUE_HEAD_DIM:-256}"
SMOLVLA_VGG_ENABLE_BASELINE_TRACE="${SMOLVLA_VGG_ENABLE_BASELINE_TRACE:-1}"
SMOLVLA_STAGE05_SLURM="stage05_train_stageA_real_only.slurm"
SMOLVLA_STAGE06_SLURM="stage06_train_stageB_jepa_mix.slurm"
SMOLVLA_STAGE07_SLURM="stage07_vgg_gatecheck.slurm"
SMOLVLA_STAGE08_SLURM="stage08_train_stageC_vgg_aux.slurm"
SMOLVLA_STAGE09_SLURM="stage09_final_eval_and_bundle.slurm"
SMOLVLA_STAGE11_SLURM="stage11_slurm_orchestration.slurm"
SMOLVLA_STAGE11_ENABLED="${SMOLVLA_STAGE11_ENABLED:-0}"

SMOLVLA_VGG_GATE_JSON="${SMOLVLA_VGG_GATE_JSON:-${SMOLVLA_REPORT_ROOT}/phase09_gatecheck.json}"
SMOLVLA_VGG_GATE_MIN_VALUE_GRAD="${SMOLVLA_VGG_GATE_MIN_VALUE_GRAD:-1.0e-8}"
SMOLVLA_VGG_GATE_MAX_BASE_FLOW_DIFF="${SMOLVLA_VGG_GATE_MAX_BASE_FLOW_DIFF:-10.0}"
SMOLVLA_VGG_GATE_SKIP_FLOW_CHECK="${SMOLVLA_VGG_GATE_SKIP_FLOW_CHECK:-0}"
SMOLVLA_VGG_GATE_FORCE_VALIDATE="${SMOLVLA_VGG_GATE_FORCE_VALIDATE:-0}"
SMOLVLA_VGG_MATCH_WARMUP_STEPS="${SMOLVLA_VGG_MATCH_WARMUP_STEPS:-200}"
SMOLVLA_VGG_MATCH_WEIGHT="${SMOLVLA_VGG_MATCH_WEIGHT:-0.05}"
SMOLVLA_VGG_TRACE_MAX_STEPS="${SMOLVLA_VGG_TRACE_MAX_STEPS:-6}"
SMOLVLA_VGG_TRACE_MAX_BATCH="${SMOLVLA_VGG_TRACE_MAX_BATCH:-2}"
SMOLVLA_VGG_VALUE_HEAD_STEPS="${SMOLVLA_VGG_VALUE_HEAD_STEPS:-6}"
SMOLVLA_VGG_VALUE_HEAD_SEED="${SMOLVLA_VGG_VALUE_HEAD_SEED:-0}"
SMOLVLA_VGG_VALUE_HEAD_MIN_GRAD="${SMOLVLA_VGG_VALUE_HEAD_MIN_GRAD:-1.0e-8}"
SMOLVLA_VGG_MATCH_TRACE_CAP="${SMOLVLA_VGG_MATCH_TRACE_CAP:-3}"

# Post-train eval uses the same push-v3 protocol as phase06; default checkpoint is still the base HF id.
SMOLVLA_FINAL_EVAL_CHECKPOINT="${SMOLVLA_FINAL_EVAL_CHECKPOINT:-${SMOLVLA_INIT_CHECKPOINT}}"

