#!/usr/bin/env python3
"""Orchestrate staged SmolVLA finetuning jobs with optional JEPA+VGG branches."""

from __future__ import annotations

import argparse
import os
import shlex
import json
import subprocess
import textwrap
from pathlib import Path
from typing import Any

import torch
from torch import nn


def _run(cmd: str) -> None:
    print(f"[train-orch] running: {cmd}")
    subprocess.check_call(cmd, shell=True)


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _infer_dataset_repo_id(dataset_root: Path) -> str:
    safe = str(dataset_root).strip().replace("/", "_").replace(" ", "_")
    if safe.startswith("."):
        safe = safe.lstrip(".")
    safe = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in safe)
    if not safe:
        safe = "smolvla_dataset"
    return f"local/{safe}"


def _trace_value_head(
    action_dim: int,
    value_head_dim: int,
    trace_steps: int,
    seed: int = 0,
) -> dict[str, Any]:
    if action_dim <= 0 or trace_steps <= 0 or value_head_dim <= 0:
        return {
            "ok": False,
            "reason": "invalid_dimensions",
            "grad_norm": 0.0,
            "value": 0.0,
        }

    torch.manual_seed(seed)
    value_head = nn.Sequential(
        nn.Linear(action_dim * trace_steps, value_head_dim),
        nn.SiLU(),
        nn.Linear(value_head_dim, 1),
    )
    x_t = torch.randn((1, trace_steps, action_dim), requires_grad=True)
    scalar = value_head(x_t.reshape(1, -1)).mean()
    grad = torch.autograd.grad(scalar, x_t, allow_unused=True, create_graph=False)[
        0
    ]
    grad_norm = float(grad.abs().mean()) if grad is not None else 0.0
    return {
        "ok": grad is not None,
        "grad_norm": grad_norm,
        "value": float(scalar.item()),
        "value_head_weight_l2": float(sum(p.pow(2).sum().item() for p in value_head.parameters())),
        "value_head_shape": [int(v) for v in x_t.shape],
    }


def _gate_is_disabled(gate_json: Path | None) -> tuple[bool, str | None, dict[str, Any]]:
    if not gate_json or not gate_json.exists():
        return True, "missing_gate_json", {}
    try:
        gate = json.loads(gate_json.read_text(encoding="utf-8"))
    except Exception as exc:
        return True, f"gate_parse_error:{exc}", {}
    if not gate.get("gate_ok", False):
        return True, "gate_ok_false", gate
    if gate.get("contract_ok") is False:
        return True, "contract_check_failed", gate
    return False, None, gate


def _write_vgg_aux_sitecustomize(path: Path, plan_path: Path) -> None:
    script = textwrap.dedent(
        """\
        # This file is generated by train_smolvla_vggflow.py for StageC only.
        from __future__ import annotations
        
        import copy
        import json
        import os
        import torch

        from torch import nn
        from lerobot.policies.smolvla import modeling_smolvla
        from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy
        from lerobot.utils.constants import OBS_LANGUAGE_ATTENTION_MASK, OBS_LANGUAGE_TOKENS
        
        PLAN_PATH = "__PLAN_PATH__"
        _PLAN = None
        try:
            if PLAN_PATH and os.path.exists(PLAN_PATH):
                with open(PLAN_PATH, "r", encoding="utf-8") as f:
                    _PLAN = json.load(f)
        except Exception:
            _PLAN = None


        def _safe_state(obj):
            return getattr(obj, "_vgg_aux_state", None)


        def _batch_device(batch):
            for value in batch.values():
                if torch.is_tensor(value):
                    return value.device
            return torch.device("cpu")

        def _call_denoise_step(model, x_t, prefix_pad_masks, past_key_values, t_tensor):
            for kwargs in [
                {
                    "x_t": x_t,
                    "prefix_pad_masks": prefix_pad_masks,
                    "past_key_values": past_key_values,
                    "timestep": t_tensor,
                },
                {
                    "x_t": x_t,
                    "prefix_pad_masks": prefix_pad_masks,
                    "past_key_values": past_key_values,
                    "timesteps": t_tensor,
                },
                {
                    "x_t": x_t,
                    "prefix_pad_masks": prefix_pad_masks,
                    "past_key_values": past_key_values,
                    "time": t_tensor,
                },
                {
                    "x_t": x_t,
                    "prefix_pad_masks": prefix_pad_masks,
                    "past_key_values": past_key_values,
                    "t": t_tensor,
                },
            ]:
                try:
                    out = model.denoise_step(**kwargs)
                except TypeError:
                    continue
                if isinstance(out, tuple):
                    return out[0]
                return out
            out = model.denoise_step(prefix_pad_masks, past_key_values, x_t, t_tensor)
            return out[0] if isinstance(out, tuple) else out

        def _build_prefix(model, batch):
            images, img_masks = model.prepare_images(batch)
            state = model.prepare_state(batch)
            lang_tokens = batch[OBS_LANGUAGE_TOKENS]
            lang_masks = batch[OBS_LANGUAGE_ATTENTION_MASK]
            if lang_tokens is None or lang_masks is None:
                raise RuntimeError("missing language fields in batch")
            if not lang_tokens.numel():
                raise RuntimeError("language tensors are empty")
            prefix_embs, prefix_pad_masks, prefix_att_masks = model.embed_prefix(
                images=images,
                img_masks=img_masks,
                lang_tokens=lang_tokens,
                lang_masks=lang_masks,
                state=state,
            )
            attention_mask = modeling_smolvla.make_att_2d_masks(prefix_pad_masks, prefix_att_masks)
            position_ids = torch.cumsum(prefix_pad_masks, dim=1) - 1
            _, past_key_values = model.vlm_with_expert.forward(
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_values=None,
                inputs_embeds=[prefix_embs, None],
                use_cache=model.config.use_cache,
                fill_kv_cache=True,
            )
            return state, past_key_values, prefix_pad_masks

        def _get_policy_state(policy):
            state = _safe_state(policy)
            if state is None:
                state = {
                    "plan": _PLAN,
                    "step": 0,
                    "base_model": None,
                    "value_head": None,
                }
                policy._vgg_aux_state = state
            return state

        def _ensure_value_head(policy):
            policy_state = _get_policy_state(policy)
            plan = policy_state.get("plan") or {}
            action_dim = int(plan.get("action_dim", policy.model.config.max_action_dim))
            trace_cap = max(1, int(plan.get("trace_cap", 3)))
            value_head_dim = max(1, int(plan.get("value_head_dim", 256)))
            value_head_input_dim = action_dim * min(
                trace_cap,
                int(policy.model.config.chunk_size),
            )
            vh = policy_state.get("value_head")
            if vh is None or not hasattr(vh, "to"):
                vh = nn.Sequential(
                    nn.Linear(value_head_input_dim, value_head_dim),
                    nn.SiLU(),
                    nn.Linear(value_head_dim, 1),
                )
                policy_state["value_head"] = vh
            return vh, action_dim, trace_cap

        def _ensure_base_model(policy):
            policy_state = _get_policy_state(policy)
            base_model = policy_state.get("base_model")
            if base_model is None or base_model is not policy.model:
                base_model = copy.deepcopy(policy.model)
                base_model.eval()
                for p in base_model.parameters():
                    p.requires_grad = False
                policy_state["base_model"] = base_model
            return base_model

        def _compute_vgg_terms(policy, batch):
            plan = _PLAN or {}
            policy_state = _get_policy_state(policy)
            if not plan or not plan.get("enabled", False):
                return None
            warmup = max(0, int(plan.get("match_warmup", 0)))
            match_weight = float(plan.get("match_weight", 0.0))
            value_head_weight = float(plan.get("value_head_weight", match_weight))

            if policy_state["step"] < warmup:
                policy_state["step"] += 1
                base_device = _batch_device(batch)
                return {
                    "match_loss": torch.tensor(0.0, device=base_device),
                    "value_loss": torch.tensor(0.0),
                    "aux_total": torch.tensor(0.0, device=base_device),
                    "aux_scale": 0.0,
                    "step": policy_state["step"],
                }

            model = policy.model
            base_model = _ensure_base_model(policy)
            value_head, action_dim, trace_cap = _ensure_value_head(policy)
            trace_steps = max(1, int(plan.get("value_head_steps", 6)))
            dt = -1.0 / float(trace_steps)

            state = model.prepare_state(batch)
            _, past_key_values, prefix_pad_masks = _build_prefix(model, batch)
            with torch.no_grad():
                _, base_past_key_values, _ = _build_prefix(base_model, batch)

            bsize = state.shape[0]
            device = state.device
            x_t = model.sample_noise((bsize, model.config.chunk_size, model.config.max_action_dim), device=device)
            x_t_base = x_t.detach().clone()
            value_head = value_head.to(device)

            residual = torch.tensor(0.0, device=device)
            for step in range(trace_steps):
                t_tensor = torch.full((bsize,), 1.0 + step * dt, device=device, dtype=torch.float32)
                v_t = _call_denoise_step(
                    model=model,
                    x_t=x_t,
                    prefix_pad_masks=prefix_pad_masks,
                    past_key_values=past_key_values,
                    t_tensor=t_tensor,
                )
                with torch.no_grad():
                    v_base = _call_denoise_step(
                        model=base_model,
                        x_t=x_t_base,
                        prefix_pad_masks=prefix_pad_masks,
                        past_key_values=base_past_key_values,
                        t_tensor=t_tensor,
                    )
                if v_t.shape[-1] < action_dim or v_base.shape[-1] < action_dim:
                    return None
                residual = residual + ((v_t[:, :, :action_dim] - v_base[:, :, :action_dim]) ** 2).mean()
                x_t = x_t + dt * v_t
                x_t_base = x_t_base + dt * v_base

            match_loss = residual / float(trace_steps)
            trace_cap = min(trace_cap, int(x_t.shape[1]))
            value_input = x_t[:, :trace_cap, :action_dim].reshape(bsize, -1)
            if value_input.shape[-1] != value_head[0].in_features:
                return None
            value_loss = -value_head(value_input).mean()
            aux_scale = 1.0
            if warmup > 0:
                aux_scale = min(1.0, max(0.0, float(policy_state["step"] - warmup) / max(1, warmup)))

            policy_state["step"] += 1
            return {
                "match_loss": match_loss,
                "value_loss": value_loss,
                "aux_scale": aux_scale,
                "aux_total": aux_scale * (match_weight * match_loss + value_head_weight * value_loss),
            }

        def _patched_forward(self, batch, noise=None, time=None, reduction="mean"):
            loss, out = _ORIGINAL_FORWARD(self, batch, noise=noise, time=time, reduction=reduction)
            policy_state = _get_policy_state(self)
            if not policy_state.get("plan", {}).get("enabled", False):
                return loss, out
            if not hasattr(self, "training") or not self.training:
                return loss, out
            try:
                aux = _compute_vgg_terms(self, batch)
                if aux is None:
                    return loss, out
                aux_total = aux["aux_total"]
                if aux_total is None:
                    return loss, out
                if isinstance(loss, torch.Tensor) and loss.ndim == 0:
                    total = loss + aux_total
                else:
                    total = loss + aux_total
                out["vgg_aux_match_loss"] = float(aux["match_loss"].detach().item()) if torch.is_tensor(aux["match_loss"]) else 0.0
                out["vgg_aux_value_loss"] = float(aux["value_loss"].detach().item()) if torch.is_tensor(aux["value_loss"]) else 0.0
                out["vgg_aux_total"] = float(aux["aux_total"].detach().item()) if torch.is_tensor(aux["aux_total"]) else 0.0
                out["vgg_aux_scale"] = float(aux["aux_scale"])
                out["vgg_aux_step"] = int(policy_state["step"])
                return total, out
            except Exception:
                return loss, out

        if _PLAN is not None and _PLAN.get("enabled", False):
            _ORIGINAL_FORWARD = SmolVLAPolicy.forward
            SmolVLAPolicy.forward = _patched_forward
        """
    )
    script = script.replace("__PLAN_PATH__", str(plan_path).replace("\\", "/"))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(script, encoding="utf-8")


def _build_base_policy_cmd(
    train_root: Path,
    output_dir: Path,
    args,
) -> str:
    ckpt = args.checkpoint
    repo_id = _infer_dataset_repo_id(train_root)
    return (
        f"{args.lerobot_train_bin} "
        f"--policy.type smolvla "
        f"--policy.pretrained_path {ckpt} "
        f"--policy.load_vlm_weights true "
        f"--policy.vlm_model_name HuggingFaceTB/SmolVLM2-500M-Instruct "
        f"--policy.expert_width_multiplier 0.5 "
        f"--policy.self_attn_every_n_layers 0 "
        f"--policy.n_action_steps 1 "
        f"--dataset.root {train_root} "
        f"--dataset.repo_id {repo_id} "
        f"--policy.max_steps {args.max_steps} "
        f"--policy.report_to none "
        f"--policy.output_dir {output_dir}"
    )


def _run_vgg_aux(
    gate_json: Path | None,
    output_dir: Path,
    args,
) -> int:
    vgg_aux_dir = output_dir / "vgg_aux"
    vgg_aux_dir.mkdir(parents=True, exist_ok=True)
    gate = {"gate_ok": False}
    disabled_reason: str | None = None

    if gate_json and gate_json.exists():
        try:
            gate = json.loads(gate_json.read_text(encoding="utf-8"))
        except Exception as exc:
            gate = {"gate_ok": False, "error": str(exc)}
        if not gate.get("gate_ok", False):
            disabled_reason = "gate_ok false"
        if gate.get("contract_ok") is False:
            disabled_reason = "contract_check_failed"

    if disabled_reason is None:
        disabled, disabled_reason_parsed, _ = _gate_is_disabled(gate_json)
        if disabled:
            disabled_reason = disabled_reason_parsed

    if disabled_reason:
        payload = {
            "enabled": False,
            "reason": disabled_reason,
            "gate": gate,
        }
        _write_json(vgg_aux_dir / "disabled_reason.json", payload)
        return 0

    action_dim = int(gate.get("velocity_shape", [0, 0, 0])[-1]) if gate.get("velocity_shape") else args.value_head_dim
    if action_dim <= 0:
        action_dim = args.value_head_dim

    probe = _trace_value_head(
        action_dim=action_dim,
        value_head_dim=args.value_head_dim,
        trace_steps=max(1, args.value_head_steps),
        seed=args.value_head_seed,
    )
    _write_json(vgg_aux_dir / "value_head_probe.json", probe)
    if not probe["ok"] or probe["grad_norm"] < args.value_head_min_grad:
        payload = {
            "enabled": False,
            "reason": "value_head_probe_failed",
            "value_head_probe": probe,
            "gate": gate,
        }
        _write_json(vgg_aux_dir / "disabled_reason.json", payload)
        return 0

    match_plan = {
        "enabled": True,
        "match_weight": float(args.match_weight),
        "match_warmup": int(args.match_warmup),
        "value_head_dim": int(args.value_head_dim),
        "value_head_steps": int(args.value_head_steps),
        "value_head_seed": int(args.value_head_seed),
        "trace_cap": max(1, int(args.trace_cap)),
        "action_dim": int(action_dim),
        "value_head_weight": float(args.match_weight),
        "value_head_ok": probe["ok"],
        "value_head_grad_norm": float(probe["grad_norm"]),
        "gate": gate,
        "plan_source": "train_smolvla_vggflow.py",
    }
    _write_json(vgg_aux_dir / "match_objective_plan.json", match_plan)

    config_payload = {
        "match_weight": args.match_weight,
        "match_warmup": args.match_warmup,
        "value_head_dim": args.value_head_dim,
        "value_head_steps": args.value_head_steps,
        "value_head_seed": args.value_head_seed,
        "trace_cap": args.trace_cap,
        "gate_json": str(gate_json) if gate_json else "",
        "output_dir": str(vgg_aux_dir),
    }
    _write_json(vgg_aux_dir / "vgg_aux_config.json", config_payload)

    sitecustomize = vgg_aux_dir / "sitecustomize.py"
    plan_path = vgg_aux_dir / "match_objective_plan.json"
    _write_vgg_aux_sitecustomize(sitecustomize, plan_path)

    if args.dry_run:
        env_prefix = f"SMOLVLA_VGG_AUX_PLAN={shlex.quote(str(plan_path))}"
        cmd = f"{env_prefix} {_build_base_policy_cmd(Path(os.path.expanduser(args.real_data_root)), vgg_aux_dir, args)}"
        print(cmd)
        print(f"[train-orch] VGG auxiliary config written: {vgg_aux_dir}")
        return 0

    existing_py_path = os.environ.get("PYTHONPATH", "")
    combined_path = str(vgg_aux_dir)
    if existing_py_path:
        combined_path = f"{combined_path}:{existing_py_path}"
    env_prefix = (
        f"PYTHONPATH={shlex.quote(combined_path)} "
        f"SMOLVLA_VGG_AUX_PLAN={shlex.quote(str(plan_path))} "
    )
    cmd = (
        f"{env_prefix}"
        f"{_build_base_policy_cmd(Path(os.path.expanduser(args.real_data_root)), vgg_aux_dir, args)}"
    )
    _run(cmd)
    _write_json(vgg_aux_dir / "completed.json", {"enabled": True, "status": "completed"})
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["stageA", "stageB", "stageC"], required=True)
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--lerobot-env", required=True)
    parser.add_argument("--real-data-root", required=True)
    parser.add_argument("--jepa-data-root", default="")
    parser.add_argument("--output-dir", default="artifacts/train_stage")
    parser.add_argument("--max-steps", type=int, default=5000)
    parser.add_argument("--gate-json", default="")
    parser.add_argument("--match-weight", type=float, default=0.05)
    parser.add_argument("--match-warmup", type=int, default=200)
    parser.add_argument("--value-head-dim", type=int, default=256)
    parser.add_argument("--value-head-steps", type=int, default=6)
    parser.add_argument("--value-head-seed", type=int, default=0)
    parser.add_argument("--value-head-min-grad", type=float, default=1.0e-8)
    parser.add_argument("--trace-cap", type=int, default=3)
    parser.add_argument("--lerobot-train-bin", default="")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    args.lerobot_train_bin = (
        str(os.path.expanduser(args.lerobot_train_bin))
        if args.lerobot_train_bin
        else str(Path(args.lerobot_env) / "bin" / "lerobot-train")
    )
    real_data_root = Path(os.path.expanduser(args.real_data_root))
    jepa_data_root = Path(os.path.expanduser(args.jepa_data_root)) if args.jepa_data_root else None
    output_root = Path(os.path.expanduser(args.output_dir))
    output_root.mkdir(parents=True, exist_ok=True)
    gate_json = Path(args.gate_json) if args.gate_json else None

    if args.mode in {"stageB", "stageC"} and not real_data_root.exists():
        print(f"[train-orch] stage data root missing: {real_data_root}")
        return 0

    if args.mode == "stageA":
        if not real_data_root.exists():
            print(f"[train-orch] stageA missing real data root: {real_data_root}")
            return 0
        cmd = _build_base_policy_cmd(real_data_root, output_root, args)
        if args.dry_run:
            print(cmd)
            return 0
        _run(cmd)
        return 0

    if args.mode == "stageB":
        if not jepa_data_root or not jepa_data_root.exists():
            print(f"[train-orch] stageB synthetic data root unavailable: {jepa_data_root}")
            return 0
        cmd = _build_base_policy_cmd(jepa_data_root, output_root / "jepa_mix", args)
        if args.dry_run:
            print(cmd)
            return 0
        _run(cmd)
        return 0

    if args.mode == "stageC":
        return _run_vgg_aux(gate_json, output_root, args)

    raise RuntimeError(f"unknown mode {args.mode}")


if __name__ == "__main__":
    raise SystemExit(main())
